/**
 * 邮箱白名单策略。
 *
 * 站点只接受本人经营的邮箱系统 + Gmail + QQ：
 *   - Hypermail（@hypermail.kdns.fr）
 *   - Gmail（含 googlemail.com）
 *   - QQ（含 foxmail.com）
 *
 * 微软邮箱（outlook / hotmail / live / msn …）与各类临时邮箱一律禁止。
 * 老用户若用了其它邮箱，需要在 EMAIL_POLICY_DEADLINE 之前换绑，
 * 否则到期后将被禁止使用（但始终允许登录去换绑，避免死锁）。
 */

/** 允许的邮箱域名（小写） */
export const ALLOWED_EMAIL_DOMAINS = [
  "hypermail.kdns.fr",
  "gmail.com",
  "googlemail.com",
  "qq.com",
  "foxmail.com",
] as const;

/** 推荐邮箱域名：换绑时优先推荐站长的 Hypermail */
export const RECOMMENDED_EMAIL_DOMAIN = "hypermail.kdns.fr";

/** 微软系邮箱：单独识别，给出更明确的提示 */
export const MICROSOFT_EMAIL_DOMAINS = [
  "outlook.com",
  "hotmail.com",
  "live.com",
  "live.cn",
  "live.hk",
  "msn.com",
  "microsoft.com",
  "office365.com",
  "outlook.cn",
  "outlook.hk",
  "passport.com",
  "windowslive.com",
  "hotmail.co.uk",
  "hotmail.fr",
  "hotmail.de",
  "hotmail.it",
  "hotmail.es",
  "hotmail.ca",
  "hotmail.com.hk",
  "hotmail.com.tw",
  "live.co.uk",
  "live.fr",
  "live.de",
  "live.it",
  "live.nl",
  "live.no",
  "live.se",
  "live.com.au",
  "live.ca",
  "live.ru",
  "live.dk",
  "live.com.mx",
] as const;

/** 常见的临时 / 一次性邮箱域名（判断不穷举，但不影响白名单判定） */
export const TEMP_EMAIL_DOMAINS = [
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "10minutemail.com",
  "10minmail.com",
  "guerrillamail.com",
  "guerrillamail.info",
  "mailinator.com",
  "maildrop.cc",
  "yopmail.com",
  "trashmail.com",
  "throwawaymail.com",
  "getnada.com",
  "dispostable.com",
  "sharklasers.com",
  "spam4.me",
  "grr.la",
  "guerrillamail.biz",
  "pokemail.net",
  "mintemail.com",
  "emailondeck.com",
  "fakeinbox.com",
  "tempinbox.com",
  "mohmal.com",
  "mytemp.email",
  "tempail.com",
  "tempmail.net",
  "tempmailaddress.com",
  "jetable.org",
  "spambox.us",
  "33mail.com",
  "harakirimail.com",
  "mailnesia.com",
  "mailcatch.com",
  "inboxkitten.com",
  "emailsensei.com",
  "guerrillamail.de",
  "bump.email",
  "tmpmail.org",
  "tmpmail.net",
  "burnermail.io",
  "anonymbox.com",
  "spamgourmet.com",
  "mail-temp.com",
  "tempemail.net",
  "emailfake.com",
  "fakemail.net",
  "fakemailgenerator.com",
  "throwawaymail.net",
  "zohomail.tk",
  "guerrillamailblock.com",
  "mailmetrash.com",
  "trashmail.net",
  "trashmail.me",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "spamspot.com",
  "spamfree24.org",
  "spamherelots.com",
  "spamthis.co.uk",
  "superrito.com",
  "suremail.info",
  "tempomail.fr",
  "tempsky.com",
  "temporarymail.com",
  "temporaryemail.net",
  "temporaryemail.us",
  "tempmailo.com",
  "tempmailplus.com",
  "temporarily.de",
  "temporaryinbox.com",
  "temporary-mail.net",
  "tempymail.com",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wuzup.net",
  "wuzupmail.net",
  "yopmail.fr",
  "yopmail.net",
  "youmailr.com",
  "zhaowei.net",
  "zoemail.org",
  "zomg.info",
  "1secmail.com",
  "1secmail.net",
  "1secmail.org",
  "20minutemail.com",
  "30minutemail.com",
  "2prong.com",
  "4warding.com",
  "4warding.net",
  "4warding.org",
  "5mail.io",
  "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.com",
  "ctrlq.org",
  "eelmail.com",
  "email64.com",
  "emailfake.xyz",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "emailtemporario.com.br",
  "fackme.gq",
  "fakemail.fr",
  "fakemailgenerator.de",
  "fakingemail.com",
  "fastacura.com",
  "fastchevy.com",
  "fastchrysler.com",
  "fastkawasaki.com",
  "fastmazda.com",
  "fastmitsubishi.com",
  "fastnissan.com",
  "fastsubaru.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "filzmail.com",
  "fixmail.tk",
  "freemails.eu",
  "hat-geld.de",
  "hulapla.com",
  "imails.info",
  "inboxalias.com",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",
  "insorg-mail.info",
  "junk1e.com",
  "kasmail.com",
  "kaspop.com",
  "klzlk.com",
  "mail-temporaire.fr",
  "mailforspam.com",
  "mailhazard.com",
  "mailhazard.net",
  "mailhazard.us",
  "mailimate.com",
  "mailin8r.com",
  "mailinator.net",
  "mailinator.org",
  "mailinator2.com",
  "mailincubator.com",
  "mailismagic.com",
  "maill.de",
  "mailsac.com",
  "mailsiphon.com",
  "mailtothis.com",
  "mailtrash.net",
  "mailzilla.com",
  "mailzilla.org",
  "makemetheking.com",
  "manybrain.com",
  "mfsa.ru",
  "mierdamail.com",
  "migmail.pl",
  "migmail.net",
  "nada.email",
  "nobulk.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.xl.cx",
  "nomail2me.com",
  "nospam4.us",
  "nospamfor.us",
  "nospamthanks.info",
  "notmailinator.com",
  "notsharingmy.info",
  "nowhere.org",
  "nurfuerspam.de",
  "nus.edu.sg",
  "objectmail.com",
  "obobbo.com",
  "onemail.info",
  "oneoffemail.com",
  "oneoffmail.com",
  "oopi.org",
  "opayq.com",
  "ourklips.com",
  "pancakemail.com",
  "pjjkp.com",
  "plexolan.de",
  "politikerclub.de",
  "poofy.org",
  "privacy.net",
  "proxymail.eu",
  "putthisinyourspamdatabase.com",
  "pwrby.com",
  "quickinbox.com",
  "rcpt.at",
  "reallymymail.com",
  "realtyalerts.ca",
  "receiveee.com",
  "recipeforbliss.com",
  "recursor.net",
  "recyclemail.dk",
  "regbypass.com",
  "regbypass.comsafe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "schafmail.de",
  "schrott-email.de",
  "secretemail.de",
  "secure-mail.biz",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "shhmail.com",
  "sify.com",
  "smapfree24.com",
  "sneakemail.com",
  "sneakmail.de",
  "sofimail.com",
  "sofort-mail.de",
  "softpls.asia",
  "solvemail.info",
  "spamail.de",
  "spamarrest.com",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambuster.es",
  "spamcero.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfighter.cf",
  "spamfree.eu",
  "spamgoes.in",
  "spamhereplease.com",
  "spamhole.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spampoo.com",
  "spambo.de",
  "spamsalad.in",
  "spamslicer.com",
  "spamstack.net",
  "spamthisplease.com",
  "spamtroll.net",
  "spamwc.de",
  "spam.yourspamgoestohere.info",
  "supergreatmail.com",
  "supermailer.jp",
  "tecomail.com",
  "telecomix.pl",
  "temporaryforwarding.com",
  "thankyou2010.com",
  "thedoghousemail.com",
  "thelimestones.com",
  "toomail.biz",
  "topranklist.de",
  "trash-amil.com",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trash2009.com",
  "trashemail.de",
  "trashinbox.com",
  "trashmail.at",
  "trashmail.io",
  "trashmail.org",
  "trashymail.com",
  "trashymail.net",
  "trillianpro.com",
  "tyldd.com",
  "uggsrock.com",
  "umail.net",
  "uroid.com",
  "us.af",
  "valemail.net",
  "venompen.com",
  "veryrealemail.com",
  "viralplays.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "webemail.me",
  "webm4il.info",
  "webuser.in",
  "wee.my",
  "wetrainbayarea.com",
  "wexample.com",
  "wh4f.org",
  "whatpaas.com",
  "whatsaas.com",
  "whopy.com",
  "willhackforfood.biz",
  "wmail.club",
  "writeme.us",
  "wronghead.com",
  "wuzupmail.com",
  "xemaps.com",
  "xmaily.com",
  "xoxy.net",
  "yep.it",
  "yogamaven.com",
  "yomail.info",
  "yopmail.org",
  "yourdomain.com",
  "ypmail.webarnak.fr.eu.org",
  "z1p.biz",
  "zaq.ne.jp",
  "zehnminuten.de",
  "zehnminutenmail.de",
  "zetmail.com",
  "zheeb.com",
  "zoemail.com",
  "zoemail.net",
  "zoho.com",
] as const;

/**
 * 换绑截止日期。用「年-月-日」字符串，按 UTC+8 判定，
 * 避免服务器时区不同导致结果不一致。
 */
export const EMAIL_POLICY_DEADLINE = "2026-10-15";

export type EmailPolicyReason =
  | "invalid"
  | "microsoft"
  | "temporary"
  | "notAllowed";

export interface EmailPolicyResult {
  ok: boolean;
  /** domain：解析出的域名（小写），解析失败时为 "" */
  domain: string;
  reason?: EmailPolicyReason;
}

function domainOf(email: string): string {
  const at = email.trim().toLowerCase().lastIndexOf("@");
  if (at < 0) return "";
  return email.trim().toLowerCase().slice(at + 1);
}

/** 判断邮箱是否被允许。只看域名；子域名一律不通过（避免 *.mail.ru 之类绕过）。 */
export function checkEmailAllowed(email: string): EmailPolicyResult {
  const domain = domainOf(email);
  if (!domain) return { ok: false, domain, reason: "invalid" };

  if ((ALLOWED_EMAIL_DOMAINS as readonly string[]).includes(domain)) {
    return { ok: true, domain };
  }
  if ((MICROSOFT_EMAIL_DOMAINS as readonly string[]).includes(domain)) {
    return { ok: false, domain, reason: "microsoft" };
  }
  if ((TEMP_EMAIL_DOMAINS as readonly string[]).includes(domain)) {
    return { ok: false, domain, reason: "temporary" };
  }
  return { ok: false, domain, reason: "notAllowed" };
}

/** 当前时间（毫秒）是否已过了换绑截止日。按 UTC+8 判定。 */
export function isPastEmailDeadline(now = Date.now()): boolean {
  // UTC+8 = UTC 时间 +8 小时
  const shifted = new Date(now + 8 * 60 * 60 * 1000);
  const iso = shifted.toISOString().slice(0, 10); // YYYY-MM-DD
  return iso >= EMAIL_POLICY_DEADLINE;
}
